var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(office)/todo/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jk-9v4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/src_1m0gebc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1f5xtv6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__15ypo8t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0r5yz5t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/[root-of-the-server]__1b-m39j._.js")
R.c("server/chunks/ssr/_1tqp5_8._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(office)_todo_page_actions_0u8gy1e.js")
R.m(90501)
module.exports=R.m(90501).exports
