// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/activity" | "/board" | "/employees" | "/employees/[id]" | "/employees/new" | "/equipment" | "/equipment/[id]" | "/equipment/new" | "/field" | "/login" | "/projects/[id]" | "/projects/[id]/edit" | "/projects/new" | "/todo" | "/weather"
type AppRouteHandlerRoutes = "/api/photos/[key]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/activity": {}
  "/api/photos/[key]": { "key": string; }
  "/board": {}
  "/employees": {}
  "/employees/[id]": { "id": string; }
  "/employees/new": {}
  "/equipment": {}
  "/equipment/[id]": { "id": string; }
  "/equipment/new": {}
  "/field": {}
  "/login": {}
  "/projects/[id]": { "id": string; }
  "/projects/[id]/edit": { "id": string; }
  "/projects/new": {}
  "/todo": {}
  "/weather": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
